#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

# Display usage if less than 4 parameters passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking for scp
scp_options="-o StrictHostKeyChecking=no"

# Transfer the file to the user home directory on the server
if scp "$scp_options" -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/; then
    echo "File transferred successfully."
else
    echo "Error transferring file. Check parameters and try again."
fi
