#!/usr/bin/env bash
# This script connects to the server using ssh with the private key ~/.ssh/school and the user ubuntu.
# SSH connection using private key and user
ssh -i ~/.ssh/school ubuntu@18.208.119.244
