#!/usr/bin/env bash
# This script connects to the server using ssh with the private key ~/.ssh/school and the user ubuntu.

# Set the server IP address
server_ip="18.208.119.244"

# SSH connection using private key and user
sudo ssh -i ~/.ssh/school ubuntu@$server_ip
